file(READ "${CMAKE_SOURCE_DIR}/VERSION" FLASHVIEWER_VERSION_STRING)
string(STRIP "${FLASHVIEWER_VERSION_STRING}" FLASHVIEWER_VERSION_STRING)
string(REGEX MATCH "([0-9]+)\\.([0-9]+)\\.([0-9]+)" _ "${FLASHVIEWER_VERSION_STRING}")
set(FLASHVIEWER_VERSION_MAJOR ${CMAKE_MATCH_1})
set(FLASHVIEWER_VERSION_MINOR ${CMAKE_MATCH_2})
set(FLASHVIEWER_VERSION_PATCH ${CMAKE_MATCH_3})

configure_file(
    "${CMAKE_SOURCE_DIR}/cmake/version.h.in"
    "${CMAKE_BINARY_DIR}/generated/version.h"
    @ONLY
)
